apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-ng-config
  namespace: monitoring
data:
  syslog-ng.conf: |
    @version: 4.10
    options {
      chain_hostnames(no);
      flush_lines(0);
      use_dns(no);
      use_fqdn(no);
      keep_hostname(yes);
      log-level(debug);
      log_fifo_size(10000);
      log_msg_size(8192);
    };

    source s_network {
        udp(ip(0.0.0.0) port(514));
        tcp(ip(0.0.0.0) port(514));
    };

    destination d_alloy {
      syslog("alloy.monitoring.svc.cluster.local" transport("udp") port(514)
        template("<$PRI>$DATE $HOST $PROGRAM: $MSG\n"));
    };

    log {
      source(s_network);
      destination(d_alloy);
      destination{ stdout();};
    };
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-ng
  namespace: monitoring
  labels:
    app: syslog-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-ng
  template:
    metadata:
      labels:
        app: syslog-ng
    spec:
      containers:
      - name: syslog-ng
        image: balabit/syslog-ng:latest
        ports:
        - containerPort: 514
          name: syslog-tcp
          protocol: TCP
        - containerPort: 514
          name: syslog-udp
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /etc/syslog-ng
      volumes:
      - name: config
        configMap:
          name: syslog-ng-config
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-ng
  namespace: monitoring
  labels:
    app: syslog-ng
    bgp: "pool-a"
    bgp-announce: "true"
spec:
  selector:
    app: syslog-ng
  ports:
  - name: syslog-tcp
    protocol: TCP
    port: 514
    targetPort: 514
  - name: syslog-udp
    protocol: UDP
    port: 514
    targetPort: 514
  type: LoadBalancer
  externalTrafficPolicy: Local
