# Patch for CoreDNS Deployment - Adds redundancy with 2 replicas
# Apply with: kubectl patch deployment coredns -n kube-system --type=strategic --patch-file patch-coredns-deployment.yml

spec:
  replicas: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - kube-dns
              topologyKey: kubernetes.io/hostname
