apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.19.1
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true
        prometheus:
          enabled: true
  - repoURL: https://github.com/NPetersenDK/KubeJourney.git
    targetRevision: main
    path: argocd/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
