apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keyvault
  namespace: argocd
spec:
  project: default
  sources:
    # External Secrets Operator Helm Chart
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.11.0
      helm:
        releaseName: external-secrets
    # KeyVault configuration manifests
    - repoURL: https://github.com/NPetersenDK/KubeJourney.git
      targetRevision: main
      path: argocd/keyvault
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
