apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    # Longhorn Helm Chart
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 3
            reclaimPolicy: Delete
          defaultSettings:
            defaultReplicaCount: 3
    # Additional Longhorn manifests (ingress only)
    - repoURL: https://github.com/NPetersenDK/KubeJourney.git
      targetRevision: main
      path: argocd/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
