apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NPetersenDK/KubeJourney.git
    targetRevision: main
    path: argocd/services
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
