apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-secret-store
  namespace: external-secrets
spec:
  provider:
    azurekv:
      tenantId: "55b360d2-7de8-4a73-9936-88af4e72c2ab"
      vaultUrl: "https://netdc-kube-kv-01.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
          namespace: external-secrets
