---
# ExternalSecret for default namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: all-keyvault-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: all-keyvault-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
---
# ExternalSecret for services namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: all-keyvault-secrets
  namespace: services
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: all-keyvault-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
---
# ExternalSecret for monitoring namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: all-keyvault-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: all-keyvault-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
---
# ExternalSecret for cert-manager namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: all-keyvault-secrets
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: all-keyvault-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
