apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: all-keyvault-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  target:
    name: all-keyvault-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"